export const apps = [
  {
    id: "App Store",
    src: "appstore.png",
    alt: "App Store",
    label: "App Store",
    active: true,
    needsUpdate: false,
    breakBefore: false,
  },
  {
    id: "Calculator",
    src: "calculatorApp.png",
    alt: "Calculator",
    label: "Calculator",
    active: false,
    needsUpdate: false,
    breakBefore: false,
  },
  {
    id: "Calendar",
    src: "calenderApp.png",
    alt: "Calendar",
    label: "Calendar",
    active: false,
    needsUpdate: false,
    breakBefore: false,
  },
  {
    id: "Chrome",
    src: "chromeIcon.png",
    alt: "Chrome",
    label: "Chrome",
    active: false,
    needsUpdate: false,
    breakBefore: false,
  },
  {
    id: "calendar",
    src: "/api/placeholder/40/40",
    alt: "Calendar",
    label: "Calendar",
    active: false,
    needsUpdate: true,
    breakBefore: false,
  },
  {
    id: "contacts",
    src: "/api/placeholder/40/40",
    alt: "Contacts",
    label: "Contacts",
    active: false,
    needsUpdate: false,
    breakBefore: true,
  },
  {
    id: "appstore",
    src: "/api/placeholder/40/40",
    alt: "App Store",
    label: "App Store",
    active: false,
    needsUpdate: true,
    breakBefore: false,
  },
  {
    id: "settings",
    src: "/api/placeholder/40/40",
    alt: "Settings",
    label: "Settings",
    active: false,
    needsUpdate: false,
    breakBefore: false,
  },
  {
    id: "trash",
    src: "/api/placeholder/40/40",
    alt: "Trash",
    label: "Trash",
    active: false,
    needsUpdate: false,
    breakBefore: true,
  },
];
